# Numpy

In [1]:
# Why numpy
# speed - Numpy faster than lists 10x. By restricting size and allowed types of data
# functionality - 
# many libs depend on numpy

In [3]:
import numpy as np

an_array = np.array([3, 33, 333])
print(type(an_array))
print(an_array.shape)

<class 'numpy.ndarray'>
(3,)


In [5]:
# prefilled arry with specific value
arr = np.full((2,2),9.0)
print(arr)

eye_arr = np.eye(2,2)

[[ 9.  9.]
 [ 9.  9.]]


In [7]:
## slicing

arr = np.array([[1,2,3],[3,4,5],[5,6,7]])

slice_arr = arr[:2,1:2] # copy by reference
print(slice_arr)

# change in slice will change arr
slice_arr[0,0] = 100
print(arr)

[[2]
 [4]]
[[  1 100   3]
 [  3   4   5]
 [  5   6   7]]


In [8]:
# These two has different sizes

slice_arr_1 = arr[1,:]
slice_arr_2 = arr[1:2,:]


# Boolean indices

In [9]:
arr = np.array([[16,21,3],[3,4,25],[51,6,7]])

filter = (arr > 15)
print(filter)

[[ True  True False]
 [False False  True]
 [ True False False]]


In [10]:
print(arr[filter])

[16 21 25 51]


In [11]:
print(arr[(arr>15) & (arr<22)])

[16 21]


In [12]:
print(arr.dtype)

int64


# Statistical sorting set operations

In [14]:
print(np.mean(arr, axis=1))

print(np.median(arr, axis=1))

[ 13.33333333  10.66666667  21.33333333]
[ 16.   4.   7.]
